### ISSUE TITLE
Error running the tool when it tries to interrogate RDS SQL instance

### ISSUE THREAD

**Issue by reidca** [gregoryjordanm/awsrightsizer#15]
**Describe the bug**
ERROR:rightsizer:Error accessing key 'DBName' for instance 'my rds instance'

**To Reproduce**
Run the tool specifying the profile name

**Expected behavior**
A report?

**Desktop/Server (please complete the following information):**
 - OS: Ubuntu 16.04
 - Python Version [e.g. 3.6.5 - run python --version to get this information]
Python3.7 --version 
Python 3.7.0

**Additional context**

**Comment by ghost** [comment]
Did you not get a report? That is less a bug and more a feature. The tool is just letting you know that there is no DBName on that particular instance. That is just an error though, unless you see EXCEPTION, the tool should have continued to run.

Unless you know for certain that there is a db name to be displayed, the tool should have just marked the DBName as unknown and moved on.

**Comment by reidca** [comment]
I get an RDS report created however the contents are empty, just the headers and footer are present.
The EC2 report seems ok.

**Comment by ghost** [comment]
Ok, I've modified the error checking and error handling for the case that the name isn't present. 

Basically, if it fails to detect a name, it will alert you via an error on screen and assign the name as 'Undefined', but the code should continue to run and the report will simply say the name is undefined, but still give you a suggestion.

I have updated PyPI so can you go ahead and run ```python3 -m pip install --upgrade awsrightsizer``` and make sure you see version 1.0.4, then run the tool again. If you don't see 1.0.4, wait a few minutes and then try again.

**Comment by ghost** [comment]
Any word on this? If not, I will go ahead and close this ticket and assume it's fixed.

**Comment by reidca** [comment]
Thank you - that seems to have resolved it.

Can I make a suggestion - the use of the word "Error" in the feedback suggests that the tool has not worked (which it has). 

In this case I would suggest either "Warning" or even just "Info" because there is nothing that can be done about it and the execution completes successfully.

**Comment by ghost** [comment]
Great suggestion! I will close this ticket out an open a feature request ticket with that request.
