### ISSUE TITLE
Include the profile name in the report filename

### ISSUE THREAD

**Issue by reidca** [gregoryjordanm/awsrightsizer#18]
**Is your feature request related to a problem? Please describe.**
If you run the tool against different accounts you typically do this using the "p" switch giving it a profile name, e.g. dev or prd. 
When the reports are created however they do not include this name therefore it is impossible to understand which account they are for.

**Describe the solution you'd like**
Include the profile name in the report file name

**Describe alternatives you've considered**
You could set the output parameter each time however it would be better if this was automatic

**Comment by ghost** [comment]
I just merged a commit to add this.
