### ISSUE TITLE
AttributeError: 'Main' object has no attribute 'initconnection'

### ISSUE THREAD

**Issue by christensen143** [gregoryjordanm/awsrightsizer#21]
**Describe the bug**
When I attempt to run rightsizer it throws a Python error. Here is what I am getting:

```
chris:~$ rightsizer -k ********** -s ********** -r us-west-2 -o 20181018.csv
Traceback (most recent call last):
  File "/home/chris/.local/bin/rightsizer", line 11, in <module>
    sys.exit(main())
  File "/home/chris/.local/lib/python3.6/site-packages/rightsizer/main.py", line 158, in main
    for r in x.getec2suggestions():
  File "/home/chris/.local/lib/python3.6/site-packages/rightsizer/AwsRightSizer.py", line 93, in getec2suggestions
    cwc = self.initconnection('cloudwatch')
AttributeError: 'Main' object has no attribute 'initconnection'
```

**To Reproduce**
1. `rightsizer -k ******** -s ******** -r us-west-3 -o 20181018.csv

**Expected behavior**
Produce csv file with results.

**Screenshots**

**Desktop/Server (please complete the following information):**
 - OS: Ubuntu 18.04 desktop
 - Python Version: 3.6.6

**Additional context**

**Comment by j4ng5y** [comment]
Looking into this now.

**Comment by j4ng5y** [comment]
@christensen143 can you please pull the latest version and try again? This should be resolved with commit 1775ec0eb9350d990c98304939efaa5772cbd737.

**Comment by christensen143** [comment]
It is working now with one caveat. When running the requirements command it cannot find the requirements file. The only requirements appear to be boto3 and click. I have created another issue for that. This issue can be closed.

**Comment by christensen143** [comment]
The issue is resolved with the update. I am creating another issue for the missing requirements file.
