### ISSUE TITLE
Requirements file missing

### ISSUE THREAD

**Issue by christensen143** [gregoryjordanm/awsrightsizer#22]
**Describe the bug**
No requirements file.

**To Reproduce**
1. Clone repo
2. Follow directions for installing from source

**Expected behavior**
When running pip install -r requirements the required modules are installed.

**Screenshots**

**Desktop/Server (please complete the following information):**
- OS - Ubuntu 18.04 Desktop
- Python 3.6.6

**Additional context**

**Comment by j4ng5y** [comment]
duplicate of #23
