### ISSUE TITLE
Missing Requirements file

### ISSUE THREAD

**Issue by christensen143** [gregoryjordanm/awsrightsizer#23]
**Describe the bug**
Requirements file is missing.

**To Reproduce**
1. Clone repo
2. Follow directions for install from source including `pip install -r requirements`

**Expected behavior**
Required modules are installed.

**Screenshots**

**Desktop/Server (please complete the following information):**
 - OS: Ubuntu 18.04 Desktop
 - Python Version 3.6.6

**Additional context**

**Comment by j4ng5y** [comment]
This should be resolved with commit 7da771a99fd6dba8d166160170dd1b6436f6ebc6

**Comment by j4ng5y** [comment]
This should be resolved with 7da771a99fd6dba8d166160170dd1b6436f6ebc6
