### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by reidca** [gregoryjordanm/awsrightsizer#8]
**Describe the bug**
Error as soon as the tool is run: 

 python rightsizer.py -p dev
  File "rightsizer.py", line 57
    default=f'report_{datetime.datetime.date(datetime.datetime.now())}.csv'

**To Reproduce**
Install the tool as per the instructions but with the addition of installing the virtual environment manager because it was not previously installed.

sudo apt-get install python3-venv

**Expected behavior**
The report is generated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04

**Additional context**
There was an issue during the installation which required me to run  the install using the --user option. In addition some issue with botocore version however this did not stop the application from installing.

```
pip install -r requirements.txt --user
Collecting boto3==1.7.50 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/59/f0/22554f0fc3aafd34e189919fd6a360d440fcaa6f86dedc9aaca904c885b1/boto3-1.7.50-py2.py3-none-any.whl
Collecting botocore==1.10.50 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/d5/9f/2e701a365b5ff0e8b664d6c393f3c61c20e52bb5148bbc2e27d737b890db/botocore-1.10.50-py2.py3-none-any.whl
Collecting click==6.7 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl
Requirement already satisfied: docutils==0.14 in /home/reidca/.local/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (0.14)
Requirement already satisfied: jmespath==0.9.3 in /home/reidca/.local/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (0.9.3)
Requirement already satisfied: python-dateutil==2.7.3 in /home/reidca/.local/lib/python2.7/site-packages (from -r requirements.txt (line 6)) (2.7.3)
Requirement already satisfied: s3transfer==0.1.13 in /home/reidca/.local/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (0.1.13)
Requirement already satisfied: six==1.11.0 in /home/reidca/.local/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (1.11.0)
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /home/reidca/.local/lib/python2.7/site-packages (from s3transfer==0.1.13->-r requirements.txt (line 7)) (3.2.0)
awscli 1.15.42 has requirement botocore==1.10.42, but you'll have botocore 1.10.50 which is incompatible.
Installing collected packages: botocore, boto3, click
  Found existing installation: botocore 1.10.42
    Uninstalling botocore-1.10.42:
      Successfully uninstalled botocore-1.10.42
Successfully installed boto3-1.7.50 botocore-1.10.50 click-6.7
reidca@HQL0739:/mnt/c/Source/awsrightsizer$ python rightsizer.py -p dev
  File "rightsizer.py", line 57
    default=f'report_{datetime.datetime.date(datetime.datetime.now())}.csv'
```

**Comment by ghost** [comment]
Ok, this looks like you aren't running python 3.6.5 or greater because it's bombing at the first instance of a string interpolation that was introduced in 3.6.5. This would not be uncommon for an ubuntu system as I think the latest python version in their repos is 3.5.

If running 3.6.5+ is not feasible, let me know, I will have to create a new branch for non-3.6.5+ python installations.

Here are the instructions for installing 3.7 on an Ubuntu 16.04 system:
```# Install requirements
apt-get install -y build-essential
apt-get install -y checkinstall
apt-get install -y libreadline-gplv2-dev
apt-get install -y libncursesw5-dev
apt-get install -y libssl-dev
apt-get install -y libsqlite3-dev
apt-get install -y tk-dev
apt-get install -y libgdbm-dev
apt-get install -y libc6-dev
apt-get install -y libbz2-dev
apt-get install -y zlib1g-dev
apt-get install -y openssl
apt-get install -y libffi-dev
apt-get install -y python3-dev
apt-get install -y python3-setuptools
apt-get install -y wget

# Prepare to build
mkdir /tmp/Python37
cd /tmp/Python37

# Pull down Python 3.7, build, and install
wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
tar xvf Python-3.7.0.tar.xz
cd /tmp/Python37/Python-3.7.0
./configure
make altinstall
```

Then you should remake your virtualenv with the new python version like so:

```virtualenv -p python3.7 venv3.7``` and activate it ```. ./venv3.7/bin/activate```

Then you would just call Python like so:

```python rightsizer.py -p dev```

if you are outside your virtualenv, then you can just call it with ```python3.7 rightsizer.py -p dev```

**Comment by ghost** [comment]
I'm updating the documentation to explicitly specify that 3.6.5 is required.

**Comment by ghost** [comment]
If I don't hear back from this particular issue by the time it hits 24 hours old, I am going to go ahead and close it.

**Comment by reidca** [comment]
Thanks for the detailed and timely response. 

I had done an apt-get update and apt-get upgrade but that did not seem to install the required version of Python.

Running 'python --version' returns
Python 2.7.12

I do not understand why the latest version from the repo is not being installed.

EDIT: Just realised that Python 3 uses a separate binary. 
>python3 --version 
Python 3.5.2

So I have tried to follow your instructions. I needed a couple of extra packages, namely gcc and make.
Then running the script produces the following result:

```
Traceback (most recent call last):
  File "/tmp/Python37/Python-3.7.0/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tmp/Python37/Python-3.7.0/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/Python37/Python-3.7.0/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/tmp/Python37/Python-3.7.0/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/tmp/Python37/Python-3.7.0/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/tmp/Python37/Python-3.7.0/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
Makefile:1132: recipe for target 'altinstall' failed
make: *** [altinstall] Error 1
```

I have done some Python but nowhere near enough to understand what is happening here.
Hopefully this makes some sense to you.

Note, I did try to see whether 'zlib' was a package but it is not. I guess it's some missing library?

Thanks
Carl

**Comment by gregoryjordanm** [comment]
the zlib package in ubuntu is call zlib1g, so go ahead and do a ```sudo apt-get install zlib1g zlib1g-dev``` and retry the building from source.

**Comment by gregoryjordanm** [comment]
I won't go very deep into the differences here, but you have python version 2 installed, python has two variants (version 2 and version 3) they were purposefully made as not-compatible. Most linux distros ship with version 2.7.x and version 3 is something that the user will have to install, so it's not an issue with Ubuntu as to why you don't have python version 3. The fault I do find with Ubuntu though is the fact that if you try to install python3 via the package manager, it gives you an older (3.5) version.

**Comment by ghost** [comment]
If you don't mind using a third-party repo, deadsnakes is really good and has all the newer versions of python as a package rather than trying to build everything from source. To do this do:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.7 python3.7-venv
```

Then you will have to create a new virtual environment to run the tool in like so:
```
python3.7 -m venv venv
. ./venv/bin/activate
```

after this, you can do the ```pip install -r requirements.txt``` and then run the tool. I'm working on adding the tool to PyPI which will speed up the running of the tool, but you will still need the correct version of python.

**Comment by reidca** [comment]
This is probably really straightforward if you know what you are doing with Python but from someone who is pretty unfamiliar with this it's proving to be pretty tough.

I added the third party repo as per your instructions, installed the python 3.7 package, created the virtual environment and activated it. 

I am then in the (venv) so I know that's working.

I then went to the correct directory and did the pip requirements install and tried to run the tool.
Got exactly the same issue. Realised that it  is because the instructions still refer to 'python' which is of course version 2x.

So I changed this to 'python3 rightsizer.py [OPTIONS]'

Same problem. Checked the version of python3 which was still 3.5.2.

Realised that python3.7 has it's own binary so changed to: 'python3.7 rightsizer.py [OPTIONS]'

Now I get a missing module for boto3
```
>python3.7 rightsizer.py -p dev
Traceback (most recent call last):
  File "rightsizer.py", line 7, in <module>
    from modules import classes
  File "/mnt/c/Source/awsrightsizer/modules/classes.py", line 2, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

**Comment by ghost** [comment]
so it looks like you may have some of the step out of order...

now that you have 3.7 installed, do the following:

1. clone this repo ```git clone https://github.com/gregoryjordanm/awsrightsizer.git```
2. move into the repo ```cd awsrightsizer```
3. create your python3.7 virtualenvironment ```python3.7 -m venv venv```
4. activate that virtual environment ```source ./venv/bin/activate```
5. install the requirements ```pip install -r requirements.txt```
6. launch the code ```python rightsizer.py [whatever options]```

in the virtual environment, you don't need to specify the python version because the environment is created with only a single version. 

When you are done, issue the ```deactivate``` command to leave the virtual environment. If you want to run it again, you will have to reactivate it with step 4 again.

**Comment by reidca** [comment]
Following your steps exactly (I deleted the previous cloned repo first)

```
reidca@HQL0739:/mnt/c/Source$ git clone https://github.com/gregoryjordanm/awsrightsizer.git
Cloning into 'awsrightsizer'...
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (93/93), done.
remote: Total 129 (delta 52), reused 84 (delta 31), pack-reused 0
Receiving objects: 100% (129/129), 51.05 KiB | 0 bytes/s, done.
Resolving deltas: 100% (52/52), done.
Checking connectivity... done.
reidca@HQL0739:/mnt/c/Source$ cd awsrightsizer
reidca@HQL0739:/mnt/c/Source/awsrightsizer$ python3.7 -m venv venv
Error: Command '['/mnt/c/Source/awsrightsizer/venv/bin/python3.7', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

EDIT : Is the version of PIP tied to the version of Python? The output of pip --version is:
`pip 10.0.1 from /home/reidca/.local/lib/python2.7/site-packages/pip (python 2.7)`

Should it instead be using a version in Python3.7?

**Comment by ghost** [comment]
oh shoot, it looks like you don't have the 3.7 version of pip maybe... try a ```sudo apt-get install python3.7-pip``` first and then try again

**Comment by reidca** [comment]
Sorry this is going on and on....

```
>sudo apt-get install python3.7-pip
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package python3.7-pip
E: Couldn't find any package by glob 'python3.7-pip'
E: Couldn't find any package by regex 'python3.7-pip'
```

According to this, Pip only has the major version: https://github.com/pypa/pip/issues/4220

So this worked:
`>sudo apt-get install python3-pip`

Running the command again:
```
>python3.7 -m venv venv
Error: Command '['/mnt/c/Source/awsrightsizer/venv/bin/python3.7', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

Same issue. Does something else need to change to tell it what version of Pip to use? Otherwise it seems it is just using the same one again.

>pip --version
pip 10.0.1 from /home/reidca/.local/lib/python2.7/site-packages/pip (python 2.7)

>pip3 --version
pip 8.1.1 from /usr/lib/python3/dist-packages (python 3.5)

**Comment by ghost** [comment]
what happens if you do a ```python3.7 -m pip --version```

**Comment by reidca** [comment]
>python3.7 -m pip --version
/usr/local/bin/python3.7: No module named pip

**Comment by ghost** [comment]
do this then: 
```curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py | sudo python3.7```

**Comment by ghost** [comment]
all of this might be in vain though lol, I just updated the code to be more python3.x compatible and i'm adding it to pypi now.

It's a good learning experience for both of us though.

**Comment by reidca** [comment]
Sounds better! This is turning out to be messy.

```
sudo python3.7 get-pip.py
Traceback (most recent call last):
  File "get-pip.py", line 20649, in <module>
    main()
  File "get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
```

I have installed the zlib package using:
>sudo apt-get install zlib1g zlib1g-dev
Which worked so I don't know why the zlib isn't working.

**Comment by ghost** [comment]
ok, so I have updated the code and pushed it to PyPI. You can now just do a ```python3 -m pip install awsrightsizer --user``` and then run ```rightsizer --help```

**Comment by reidca** [comment]
rightsizer --help
ERROR:rightsizer:Python version 3.6.5 is required, you are running Python version 3.5.2
NoneType

**Comment by ghost** [comment]
Oh yeah, that is an artifact from before, let me update that.

**Comment by ghost** [comment]
ok, do a ```python3 -m pip install --upgrade awsrightsizer --user``` and then try again

**Comment by reidca** [comment]
reidca@HQL0739:/mnt/c/Source/awsrightsizer$ python3 -m pip install --upgrade awsrightsizer --user
Collecting awsrightsizer
  Using cached https://files.pythonhosted.org/packages/3c/11/c872bbe654c52c0a7571b64ec4e108746e6867ce2aff8db037f17ef665c1/awsrightsizer-1.0.0-py3-none-any.whl
Collecting boto3 (from awsrightsizer)
  Using cached https://files.pythonhosted.org/packages/d0/a6/48768566d78f51415b222f5a5a858768ebc92070f435d011121a91494e65/boto3-1.7.60-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->awsrightsizer)
  Using cached https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting botocore<1.11.0,>=1.10.60 (from boto3->awsrightsizer)
  Using cached https://files.pythonhosted.org/packages/75/bc/b47bc0b2262a2b808a8add6a46ea1338ad71fd4cc06f35ff6ac577b2b366/botocore-1.10.60-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3->awsrightsizer)
  Using cached https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1; python_version >= "2.7" (from botocore<1.11.0,>=1.10.60->boto3->awsrightsizer)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.11.0,>=1.10.60->boto3->awsrightsizer)
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1; python_version >= "2.7"->botocore<1.11.0,>=1.10.60->boto3->awsrightsizer)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Installing collected packages: jmespath, six, python-dateutil, docutils, botocore, s3transfer, boto3, awsrightsizer
Successfully installed awsrightsizer-1.0.0 boto3-1.7.60 botocore-1.10.60 docutils-0.14 jmespath-0.9.3 python-dateutil-2.7.3 s3transfer-0.1.13 six-1.11.0
You are using pip version 8.1.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
reidca@HQL0739:/mnt/c/Source/awsrightsizer$ rightsizer --help
ERROR:rightsizer:Python version 3.6.5 is required, you are running Python version 3.5.2
NoneType

**Comment by ghost** [comment]
Ok, it didn't pull the latest version (should be 1.0.1) ... try it again as I just saw the new version pop up on pypi

**Comment by reidca** [comment]
BINGO!!!!

usage: rightsizer [-h] [-p PROFILE] [-k ACCESSKEY] [-s SECRETKEY] [-r REGION]
                  [-t THRESHOLD THRESHOLD] [-q QUERY] [-o OUTPUT] [-e] [-d]

optional arguments:
  -h, --help            show this help message and exit
  -p PROFILE, --profile PROFILE
                        AWS Credentials Profile
  -k ACCESSKEY, --access-key ACCESSKEY
                        AWS Access Key Id
  -s SECRETKEY, --secret-key SECRETKEY
                        AWS Secret Access Key
  -r REGION, --region REGION
                        AWS Region
  -t THRESHOLD THRESHOLD, --threshold THRESHOLD THRESHOLD
                        The Cloudwatch [average, max] CPU usage threshold
  -q QUERY, --query-config QUERY
                        The amount of [days, period] to query Cloudwatch for
  -o OUTPUT, --output OUTPUT
                        The name/location of the csv file to output
  -e, --ec2-only        Run this tool against EC2 Instances only
  -d, --rds-only        Run this tool against RDS Instances only

**Comment by ghost** [comment]
glad to see! fortunately, the easier fix for you was something i was already working on. I am going to go ahead and close this ticket out. Feel free to open another if you have more issues.

**Comment by reidca** [comment]
Thank you for your help. Great support. I will give the tool a proper test tomorrow.
